GET http://localhost:5145

###

GET http://localhost:5145/hellous



###
GET  http ://todoapp-maria2025.azurewebsites.net

###
GET  http://todoapp-maria2025.azurewebsites.net/hellous




###

//this should give "Hello 254s"
GET http://localhost:5000

###

GET http://localhost:5000/hellous

// when starting from bin/debug/net9.0 #pory is 5000 for some reason


###
GET  http://todoapp-maria2025.azurewebsites.net


GET  http://todoapp-maria2025.azurewebsites.net/hellous