GET http://localhost:5000

###

GET http://localhost:5000/hellous



###
GET  http://todoapp-maria2025.azurewebsites.net


GET  http://todoapp-maria2025.azurewebsites.net/hellous




###

//this should give "Hello 254s"
GET http://localhost:5000

###

GET http://localhost:5000/hellous



###
GET  http://todoapp-maria2025.azurewebsites.net


GET  http://todoapp-maria2025.azurewebsites.net/hellous